#!/usr/bin/env bash
# AAMM Adoption Data Collector (5 Detection Layers)
# Usage: ./collect-adoption.sh owner/repo [output_dir]
# Collects AI adoption signals across all 5 layers from ADR-003.
# Requires GITHUB_TOKEN environment variable.
# Note: Expects readiness data already collected (reuses tree.json, recent-prs.json)

set -euo pipefail

REPO="${1:?Usage: $0 owner/repo [output_dir]}"
OUTDIR="${2:-/tmp/aamm-$(echo "$REPO" | tr '/' '-')}"
API="https://api.github.com"

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  source ~/.zshrc 2>/dev/null || true
  if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    echo "ERROR: GITHUB_TOKEN not set" >&2
    exit 1
  fi
fi

AUTH=(-H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json")
mkdir -p "$OUTDIR/adoption"

echo "=== AAMM Adoption Collector (5 Layers): $REPO ==="
echo ""

# --- L1: Repository Tree (AI config files) ---
echo "[L1] Tree scan for AI config files..."
if [[ -f "$OUTDIR/ai-config-files.txt" ]]; then
  L1_COUNT=$(wc -l < "$OUTDIR/ai-config-files.txt")
  echo "  Reusing readiness data: $L1_COUNT AI config files"
  cp "$OUTDIR/ai-config-files.txt" "$OUTDIR/adoption/L1-ai-configs.txt"
else
  # Fetch tree if not available
  DEFAULT_BRANCH=$(curl -s "${AUTH[@]}" "$API/repos/$REPO" | jq -r '.default_branch')
  curl -s "${AUTH[@]}" "$API/repos/$REPO/git/trees/$DEFAULT_BRANCH?recursive=1" > "$OUTDIR/tree.json"
  jq -r '.tree[] | select(.type == "blob") | .path' "$OUTDIR/tree.json" \
    | grep -iE '(CLAUDE\.md|claude\.md|AGENTS\.md|GEMINI\.md|copilot-instructions\.md|copilot-setup-steps\.yml|\.cursorrules|\.cursor/rules|\.claude/|\.mcp\.json|mcp\.json|\.coderabbit\.yaml|\.aiignore|\.cursorignore|\.aider|\.windsurfrules|\.continue/|\.sourcegraph/cody|\.codex/)' \
    > "$OUTDIR/adoption/L1-ai-configs.txt" || true
  L1_COUNT=$(wc -l < "$OUTDIR/adoption/L1-ai-configs.txt")
fi

# Fetch content of each AI config file
if [[ $L1_COUNT -gt 0 ]]; then
  echo "  Fetching AI config file contents..."
  while IFS= read -r f; do
    SAFE=$(echo "$f" | tr '/' '_')
    curl -s "${AUTH[@]}" "$API/repos/$REPO/contents/$f" | jq -r '.content // empty' | base64 -d > "$OUTDIR/adoption/L1-content-$SAFE" 2>/dev/null || true
    echo "    $f ($(wc -c < "$OUTDIR/adoption/L1-content-$SAFE" 2>/dev/null || echo 0) bytes)"
  done < "$OUTDIR/adoption/L1-ai-configs.txt"
fi
echo "  L1 result: $L1_COUNT AI config files"

# --- L2: Commit Metadata (Co-authored-by AI patterns) ---
echo ""
echo "[L2] Commit metadata scan..."
if [[ -f "$OUTDIR/recent-commits.json" ]]; then
  echo "  Reusing readiness data"
else
  curl -s "${AUTH[@]}" "$API/repos/$REPO/commits?per_page=50" > "$OUTDIR/recent-commits.json"
fi

# Search for AI co-author patterns (case-insensitive)
jq -r '.[] | "\(.sha[0:10]) \(.commit.message)"' "$OUTDIR/recent-commits.json" \
  | grep -iE '(co-authored-by:.*(copilot|claude|cursor|gemini|coderabbit|ai-generated))' \
  > "$OUTDIR/adoption/L2-ai-commits.txt" || true
L2_COUNT=$(wc -l < "$OUTDIR/adoption/L2-ai-commits.txt")
echo "  L2 result: $L2_COUNT AI co-authored commits"

# --- L3: PR Author Search (bot-authored PRs) ---
echo ""
echo "[L3] PR author search..."
for bot in "app/copilot-swe-agent" "app/coderabbit-ai" "Copilot"; do
  SAFE=$(echo "$bot" | tr '/' '_')
  QUERY="repo:$REPO+type:pr+author:$bot"
  curl -s "${AUTH[@]}" "$API/search/issues?q=$QUERY&per_page=10" > "$OUTDIR/adoption/L3-$SAFE.json" 2>/dev/null || echo '{"total_count":0}' > "$OUTDIR/adoption/L3-$SAFE.json"
  COUNT=$(jq '.total_count // 0' "$OUTDIR/adoption/L3-$SAFE.json")
  echo "  $bot: $COUNT PRs"
done

# Also check dependabot
QUERY="repo:$REPO+type:pr+author:app/dependabot"
curl -s "${AUTH[@]}" "$API/search/issues?q=$QUERY&per_page=5" > "$OUTDIR/adoption/L3-dependabot.json" 2>/dev/null || true
DEP_COUNT=$(jq '.total_count // 0' "$OUTDIR/adoption/L3-dependabot.json")
echo "  dependabot: $DEP_COUNT PRs"

# --- L4: PR Body Text Search ---
echo ""
echo "[L4] PR body text scan..."
if [[ ! -f "$OUTDIR/recent-prs.json" ]]; then
  curl -s "${AUTH[@]}" "$API/repos/$REPO/pulls?state=all&per_page=30&sort=updated&direction=desc" > "$OUTDIR/recent-prs.json"
fi

# Also fetch open PRs to catch recent activity
curl -s "${AUTH[@]}" "$API/repos/$REPO/pulls?state=open&per_page=30&sort=updated&direction=desc" > "$OUTDIR/adoption/L4-open-prs.json" 2>/dev/null || true

# Combine and search body text
AI_PATTERNS='Made with.?Cursor|Claude Code|Generated by Claude|copilot-swe-agent|copilot.coding.agent|@copilot|Co-Authored-By.*(Claude|Copilot|Cursor)|CURSOR_SUMMARY|coderabbit'

jq -r '.[] | "\(.number)\t\(.user.login)\t\(.title)\t\(.body // "")"' "$OUTDIR/recent-prs.json" \
  | grep -iE "$AI_PATTERNS" \
  > "$OUTDIR/adoption/L4-ai-pr-body.txt" || true

jq -r '.[] | "\(.number)\t\(.user.login)\t\(.title)\t\(.body // "")"' "$OUTDIR/adoption/L4-open-prs.json" \
  | grep -iE "$AI_PATTERNS" \
  >> "$OUTDIR/adoption/L4-ai-pr-body.txt" 2>/dev/null || true

# Deduplicate by PR number
sort -t$'\t' -k1,1 -u "$OUTDIR/adoption/L4-ai-pr-body.txt" > "$OUTDIR/adoption/L4-ai-pr-body-dedup.txt" 2>/dev/null || true
L4_COUNT=$(wc -l < "$OUTDIR/adoption/L4-ai-pr-body-dedup.txt" 2>/dev/null || echo 0)
echo "  L4 result: $L4_COUNT PRs with AI signatures in body text"

# --- L5: Submodule Traversal ---
echo ""
echo "[L5] Submodule traversal..."
if [[ -f "$OUTDIR/.gitmodules" ]]; then
  echo "  .gitmodules found. Parsing submodules..."
  # Extract submodule URLs and paths
  grep -E '(path|url)' "$OUTDIR/.gitmodules" | paste - - | while IFS= read -r line; do
    SM_PATH=$(echo "$line" | grep -oP 'path\s*=\s*\K\S+')
    SM_URL=$(echo "$line" | grep -oP 'url\s*=\s*\K\S+')
    SM_REPO=$(echo "$SM_URL" | grep -oP 'github\.com[:/]\K[^.]+' || true)

    if [[ -n "$SM_REPO" ]]; then
      echo "  Submodule: $SM_PATH → $SM_REPO"
      # Get the pinned SHA from the parent tree
      SM_SHA=$(jq -r --arg p "$SM_PATH" '.tree[] | select(.path == $p and .mode == "160000") | .sha' "$OUTDIR/tree.json")

      if [[ -n "$SM_SHA" ]]; then
        # Fetch submodule tree
        SM_TREE=$(curl -s "${AUTH[@]}" "$API/repos/$SM_REPO/git/trees/$SM_SHA?recursive=1" 2>/dev/null)
        if echo "$SM_TREE" | jq -e '.tree' > /dev/null 2>&1; then
          echo "$SM_TREE" > "$OUTDIR/adoption/L5-$(echo "$SM_REPO" | tr '/' '-')-tree.json"
          # Check for AI configs in submodule
          echo "$SM_TREE" | jq -r '.tree[] | select(.type == "blob") | .path' \
            | grep -iE '(CLAUDE\.md|\.claude/|\.mcp\.json|\.cursorrules|\.cursor/|AGENTS\.md|GEMINI\.md|copilot-instructions|\.coderabbit|\.aiignore|\.cursorignore)' \
            > "$OUTDIR/adoption/L5-$(echo "$SM_REPO" | tr '/' '-')-ai-configs.txt" || true
          SM_AI_COUNT=$(wc -l < "$OUTDIR/adoption/L5-$(echo "$SM_REPO" | tr '/' '-')-ai-configs.txt")
          echo "    AI configs in submodule: $SM_AI_COUNT"
        else
          echo "    ⚠ Submodule inaccessible (private repo or insufficient token scope)"
          echo "INACCESSIBLE: $SM_REPO (SHA: $SM_SHA)" >> "$OUTDIR/adoption/L5-inaccessible.txt"
        fi
      fi
    fi
  done
else
  echo "  No .gitmodules — no submodules"
fi

# --- Summary ---
echo ""
echo "=== Adoption Detection Summary ==="
echo "L1 (Tree):      $L1_COUNT AI config files"
echo "L2 (Commits):   $L2_COUNT AI co-authored commits"
echo "L3 (PR Author): $(jq '.total_count // 0' "$OUTDIR/adoption/L3-app_copilot-swe-agent.json" 2>/dev/null || echo 0) copilot + $(jq '.total_count // 0' "$OUTDIR/adoption/L3-app_coderabbit-ai.json" 2>/dev/null || echo 0) coderabbit + $(jq '.total_count // 0' "$OUTDIR/adoption/L3-Copilot.json" 2>/dev/null || echo 0) Copilot"
echo "L4 (PR Body):   $L4_COUNT PRs with AI signatures"
echo "L5 (Submodules): $(ls "$OUTDIR/adoption/L5-"*"-ai-configs.txt" 2>/dev/null | wc -l || echo 0) submodules checked"
echo ""
echo "Output: $OUTDIR/adoption/"
